#' Board construction source
#'
#' `board_script()` turns a saved board into the R script that rebuilds it. A
#' board's JSON is a serialization of the constructor calls that produced it --
#' every object records its constructor name, its package and a payload of
#' literals -- so the two forms carry the same information and the conversion is
#' mechanical. What this adds over a `dput()` is readability:
#'
#' * block ids become slugs of `block_name` (`global_population_filter` rather
#'   than `bsifddnw`), and every reference moves with them: links, view members,
#'   grid panels, stack members, and the payload fields blocks use to point at
#'   each other
#' * view ids likewise become slugs of the view name, carried into the `grids`
#'   keys and `active`
#' * duplicate `visible.N` state entries are collapsed (see `collapse_state()`
#'   for why they are not merely noise)
#' * a code block's `script` is emitted one source line per element, so it reads
#'   as the code it is
#' * blocks are grouped under the view that first shows them
#'
#' Do not run styler on the result. It reflows the code-block script vectors
#' into a blob; the layout here is deliberate.
#'
#' @param x A board, or the list `blockr.core::blockr_ser()` produces for one.
#' @param name Name of the function the script defines.
#' @param rename Slug the block and view ids. `FALSE` keeps the stored ids,
#'   which is what you want when comparing generated source against a stored
#'   spec byte for byte.
#' @param tidy Collapse duplicate state entries. `FALSE` reproduces the stored
#'   payload verbatim.
#' @param group Order the blocks by the view that first shows them, under a
#'   section comment. Defaults to `rename`, since both are readability moves;
#'   set it `FALSE` to keep the stored order.
#' @param ref_fields Payload field names that hold a block id, and so have to be
#'   rewritten when ids are renamed. Only these are touched: a payload value
#'   that merely coincides with an id (a `head` block stores
#'   `direction = "head"`) must not be rewritten. Any stored id the rename
#'   leaves behind raises a warning naming the field, which is how you find a
#'   block type with a reference field this does not know about.
#'
#' @return A single string: the source of a function that returns the board.
#'
#' @examples
#' \dontrun{
#' board <- blockr.core::blockr_deser(
#'   jsonlite::fromJSON("board.json", simplifyVector = FALSE)
#' )
#' cat(board_script(board, "my_board"))
#' }
#'
#' @export
board_script <- function(x, name = "board", rename = TRUE, tidy = TRUE,
                         group = rename,
                         ref_fields = default_ref_fields()) {

  spec <- as_board_spec(x)
  p <- spec[["payload"]]

  blocks <- p[["blocks"]][["payload"]]
  views <- p[["views"]][["payload"]][["views"]]
  grids <- p[["grids"]][["payload"]]

  bmap <- if (isTRUE(rename)) {
    block_id_map(blocks)
  } else {
    stats::setNames(names(blocks), names(blocks))
  }

  vmap <- if (isTRUE(rename)) {
    view_id_map(views)
  } else {
    stats::setNames(names(views), names(views))
  }

  if (isTRUE(rename)) {
    warn_dangling(blocks, bmap, ref_fields)
  }

  src <- paste0(
    name, " <- function() {\n\n",
    indent(
      paste(
        c(
          blocks_src(blocks, views, bmap, tidy, group, ref_fields),
          links_src(p[["links"]][["payload"]], bmap),
          stacks_src(p[["stacks"]][["payload"]], bmap),
          views_src(views, bmap, vmap),
          grids_src(grids, bmap, vmap),
          extensions_src(p[["extensions"]][["payload"]], bmap),
          options_src(p[["options"]][["payload"]])
        ),
        collapse = "\n\n"
      )
    ),
    "\n\n",
    indent(board_call_src(unname(vmap[[p[["views"]][["payload"]][["active"]]]]))),
    "\n}\n"
  )

  warn_unresolved(src)

  src
}

#' @param file Path to write to.
#' @param header Comment lines placed above the function. `NULL` writes a
#'   default header naming the board and the counts.
#' @rdname board_script
#' @export
write_board_script <- function(x, file, name = "board", rename = TRUE,
                               tidy = TRUE, group = rename,
                               ref_fields = default_ref_fields(),
                               header = NULL) {

  spec <- as_board_spec(x)
  src <- board_script(spec, name = name, rename = rename, tidy = tidy,
                      group = group, ref_fields = ref_fields)

  if (is.null(header)) {
    header <- default_header(spec, rename)
  }

  writeLines(sub("[ \t]+$", "", c(header, "", src)), file)

  invisible(file)
}

default_header <- function(spec, rename) {

  p <- spec[["payload"]]

  c(
    paste0("# Board construction source, generated by blockr.ops ",
           "from the stored board."),
    "#",
    sprintf("# %d blocks, %d links, %d views, %d stacks, %d extensions.",
            length(p[["blocks"]][["payload"]]),
            length(p[["links"]][["payload"]]),
            length(p[["views"]][["payload"]][["views"]]),
            length(p[["stacks"]][["payload"]]),
            length(p[["extensions"]][["payload"]])),
    if (isTRUE(rename)) c(
      "#",
      "# Block and view ids are slugs of their display names; the stored random",
      "# slugs carry no meaning and every reference to them was rewritten to",
      "# match. Set `rename = FALSE` to keep them."
    ),
    "#",
    "# Do not run styler on this file: it reflows the code-block scripts."
  )
}

warn_dangling <- function(blocks, bmap, ref_fields) {

  left <- unlist(lapply(names(blocks), function(id) {
    p <- remap_payload(blocks[[id]][["payload"]], bmap, ref_fields)
    names(dangling_ids(p, names(bmap), id))
  }))

  if (!length(left)) {
    return(invisible(NULL))
  }

  warning(
    "Block ids survive the rename in: ", paste(unique(left), collapse = ", "),
    ". Either these are reference fields missing from `ref_fields`, or a stored ",
    "value coincides with a block id. Use `rename = FALSE` if unsure.",
    call. = FALSE
  )
}

as_board_spec <- function(x) {

  if (is.list(x) && all(c("object", "payload") %in% names(x))) {
    return(x)
  }

  blockr.core::blockr_ser(x)
}

# ------------------------------------------------------------------ sections

# Blocks read in view order, under a comment naming the view that first shows
# them, so the file follows the app rather than the storage order. Blocks on no
# view (data sources, checks -- plumbing rather than panels) come last.
blocks_src <- function(blocks, views, bmap, tidy, group = TRUE,
                       ref_fields = default_ref_fields()) {

  view_of <- character()

  for (vid in names(views)) {
    members <- sub("^block_panel-", "", unlist(views[[vid]][["payload"]]))
    fresh <- setdiff(intersect(members, names(blocks)), names(view_of))
    for (m in fresh) {
      view_of[[m]] <- view_label(views[[vid]], vid)
    }
  }

  orphans <- setdiff(names(blocks), names(view_of))
  view_of[orphans] <- "Not on any view"

  order_by <- c(unlist(Map(view_label, views, names(views))), "Not on any view")

  ordered <- if (isTRUE(group)) {
    names(blocks)[order(match(view_of[names(blocks)], order_by))]
  } else {
    names(blocks)
  }

  known <- known_fields(blocks)

  chunks <- character()
  section <- ""

  for (id in ordered) {

    prefix <- ""

    if (isTRUE(group) && !identical(view_of[[id]], section)) {
      section <- view_of[[id]]
      prefix <- paste0(
        "\n  # -- ", section, " ",
        strrep("-", max(0L, 66L - nchar(section))), "\n"
      )
    }

    blk <- blocks[[id]]
    payload <- blk[["payload"]]

    if (isTRUE(tidy)) {
      payload <- collapse_state(payload, known)
    }

    chunks <- c(
      chunks,
      paste0(
        prefix,
        indent(paste0(
          name_src(bmap[[id]]), " = ",
          ctor_call_src(
            blk[["constructor"]], remap_payload(payload, bmap, ref_fields)
          )
        ))
      )
    )
  }

  paste0("blocks <- c(\n", paste(chunks, collapse = ",\n"), "\n)")
}

links_src <- function(links, bmap) {

  if (!length(links)) {
    return("links <- list()")
  }

  one <- function(id) {
    l <- links[[id]][["payload"]]
    indent(sprintf(
      "%s = blockr.core::new_link(from = %s, to = %s, input = %s)",
      name_src(id), deparse(unname(bmap[l[["from"]]])),
      deparse(unname(bmap[l[["to"]]])), deparse(l[["input"]])
    ))
  }

  paste0(
    "links <- c(\n",
    paste(vapply(names(links), one, character(1)), collapse = ",\n"),
    "\n)"
  )
}

stacks_src <- function(stacks, bmap) {

  if (!length(stacks)) {
    return("stacks <- list()")
  }

  named_list_src(
    "stacks <- list",
    vapply(
      stacks,
      function(s) ctor_call_src(s[["constructor"]], remap(s[["payload"]], bmap)),
      character(1)
    ),
    names(stacks)
  )
}

views_src <- function(views, bmap, vmap) {

  one <- function(v) {
    paste0(
      "blockr.dock::dock_view(\n",
      indent(paste0(
        "members = ", value_src(remap_panels(unlist(v[["payload"]]), bmap)),
        ",\nname = ", deparse(v[["name"]])
      )),
      "\n)"
    )
  }

  named_list_src(
    "views <- list", vapply(views, one, character(1)),
    unname(vmap[names(views)])
  )
}

grids_src <- function(grids, bmap, vmap) {
  named_list_src(
    "grids <- list",
    vapply(grids, function(g) grid_src(remap_panels(g, bmap)), character(1)),
    unname(vmap[names(grids)])
  )
}

extensions_src <- function(extensions, bmap) {

  if (!length(extensions)) {
    return("extensions <- list()")
  }

  named_list_src(
    "extensions <- list",
    vapply(
      extensions,
      function(e) ctor_call_src(e[["constructor"]], remap_panels(e[["payload"]], bmap)),
      character(1)
    ),
    names(extensions)
  )
}

options_src <- function(options) {
  paste0(
    "options <- blockr.core::new_board_options(\n",
    paste(
      vapply(
        options,
        function(o) indent(ctor_call_src(o[["constructor"]], o[["payload"]], "pkg")),
        character(1)
      ),
      collapse = ",\n"
    ),
    "\n)"
  )
}

board_call_src <- function(active) {
  paste0(
    "blockr.dock::new_dock_board(\n",
    indent(paste(
      c("blocks = blocks", "links = links", "stacks = stacks",
        "views = views", "grids = grids", "extensions = extensions",
        "options = options", paste0("active = ", deparse(active))),
      collapse = ",\n"
    )),
    "\n)"
  )
}
